### ISSUE TITLE
New Version not working.

### ISSUE THREAD

**Issue by noob2628** [R-Grigala/Craft-Shop#1]
WARNING in [eslint]
src\custom-hooks\useGetData.js
  Line 23:7:  React Hook useEffect has a missing dependency: 'collectionRef'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src\pages\ProductDetails.jsx
  Line 47:5:  React Hook useEffect has a missing dependency: 'docRef'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by R-Grigala** [comment]
new version not working for you because firebase Config.js change. best experience that firebase information has been securete, for that i used .env file and changed firebase API key  for more secured.

if you change firebaseConfig.js file with your firebaseConfig file, your project will be successful. for that you need to watch youtube video or learn firebaseConfig file create
